import type { Metadata } from "next";
import { BackToHome } from "@/components/ui/general/back-to-home";

export const metadata: Metadata = {
  title: "Play - Driving Poker",
  description: "Generated by create next app",
};

export default function PlayLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col min-h-screen bg-gray-100 dark:bg-gray-900">
      <header className="p-4 flex justify-start">
        <BackToHome />
      </header>
      <main className="flex-1 flex flex-col items-center justify-center p-4">
        {children}
      </main>
    </div>
  );
}
